### PR TITLE
Report when value in returned scan for a trailer is not a number.

### PR DESCRIPTION
**Pull request by martinkunc**
Actually the problem was that different scans can exist on different indexes in consequent scans, so we have to read trailers position for each scan.
Also reporting errors when trailer is not found to the standard error output.

### CODE REVIEW

**Comment by martinkunc** [comment]
@cpanse Hi Christian, can you please look if the changes are making sense ?

**Comment by cpanse** [comment]
> @cpanse Hi Christian, can you please look if the changes are making sense ?

@martinkunc Hoi Martin, thank you. Can you please provide me an example raw file and a R snippet?

**Comment by cpanse** [comment]
> > @cpanse Hi Christian, can you please look if the changes are making sense ?
> 
> @martinkunc Hoi Martin, thank you. Can you please provide me an example raw file and a R snippet?

@martinkunc, you can also send me the location of the raw file via cp@fgcz.ethz.ch. tnx

**Comment by cpanse** [comment]
@martinkunc my problem is you have indented the code. do you have any idea how I can see the diff?

**Comment by martinkunc** [comment]
@cpanse Oh, I can see how it looks unformatted without the white space ignoring, Please don't spend too much time on it, I will prepare another change to improve the situation. Suprisingly, providing the raw file alone needs some approval on my side, so it might take some time. I will improve my PR over the weekend.

**Comment by martinkunc** [comment]
@cpanse I attempted to fix the indentation.
The problem I was seeing was after invoking:
```
.\rawrr.exe .\TC114187_OT_scan.raw scans .\scannumbers.txt scansresults.txt
Error accessing RAWFileReader library! - Input string was not in a correct format.
```
On my raw file with Ion Trap with ESI, where the order in a particular Scan Number didn't match the initial trailer order.
I will see if I would be able to get the raw file.

**Pull request closed without merging**
